name: Test workflows

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test_my_django_project:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: '${{ secrets.DJANGO_SECRET_KEY }}'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello world
        run: |
          echo "DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}"
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install pip --upgrade
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test
