name: Test workflows

on:
  workflow_dispatch:

jobs:
  test_my_django_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello world
        run: echo "hello world"
